name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        run: |
          ssh deployuser@192.168.244.161 'mkdir -p /var/www/quizapp'
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/dist/ deployuser@192.168.244.161:/var/www/quizapp
          ssh deployuser@192.168.244.161 'sudo systemctl restart quizapp-service'


      - name: Notify Deployment Status
        run: echo 'Deployment successful!'
name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Add SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh-add private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no deployuser@192.168.244.161 'mkdir -p /var/www/quizapp'
          rsync -r --delete-after --quiet $GITHUB_WORKSPACE/dist/ deployuser@192.168.244.161:/var/www/quizapp
          ssh deployuser@192.168.244.161 'sudo systemctl restart your-app-service'

      - name: Notify Deployment Status
        run: echo 'Deployment successful!'
