name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Log Node.js version
      run: node --version

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci

    - name: Output npm debug log on failure
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug.log

    - name: Run build script if present
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
